import { AppState, Gonderi, Urun, HareketKaydi } from './types'

export const demoMagaza: Urun[] = [
  { id: 'u1', ad: 'Neon Çerçeve', aciklama: 'Profil fotoğrafın için parlak yeşil bir çerçeve.', kategori: 'sureli', fiyat: 15, sureGun: 1, efekt: { tur: 'cerceve', deger: 'neon' } },
  { id: 'u2', ad: 'Altın İsim', aciklama: 'Kullanıcı adını 24 saatliğine altın rengine boya.', kategori: 'sureli', fiyat: 30, sureGun: 1, efekt: { tur: 'adRengi', deger: 'altin' } },
  { id: 'u3', ad: 'Bahar Teması', aciklama: 'Profiline bahar renkleri kat.', kategori: 'sezonluk', fiyat: 150, sureGun: 30, efekt: { tur: 'tema', deger: 'bahar' } },
  { id: 'u4', ad: 'Yıldız Rozeti', aciklama: 'Adının yanında parlayan bir yıldız rozeti.', kategori: 'sezonluk', fiyat: 200, sureGun: 30, efekt: { tur: 'rozet', deger: 'yildiz' } },
  { id: 'u5', ad: 'Elmas Çerçeve', aciklama: 'Kalıcı ve prestijli elmas çerçeve.', kategori: 'kalici', fiyat: 800, sureGun: null, efekt: { tur: 'cerceve', deger: 'elmas' } },
  { id: 'u6', ad: 'Onay Rozeti', aciklama: 'Kalıcı topluluk onay rozeti.', kategori: 'kalici', fiyat: 1200, sureGun: null, efekt: { tur: 'rozet', deger: 'onay' } },
  { id: 'u7', ad: 'Uzun Gönderi', aciklama: '30 gün boyunca 1000 karakterlik gönderi paylaş.', kategori: 'islevsel', fiyat: 50, sureGun: 30, efekt: { tur: 'islev', deger: 'uzun_gonderi' } },
  { id: 'u8', ad: 'Gelişmiş Anket', aciklama: '30 gün boyunca 8 seçenekli anketler aç.', kategori: 'islevsel', fiyat: 80, sureGun: 30, efekt: { tur: 'islev', deger: 'gelismis_anket' } },
]

export const demoHareketler: HareketKaydi[] = [
  { id: 'h1', zaman: new Date(Date.now() - 86400000 * 5).toISOString(), aciklama: 'Hoş geldin hediyesi', miktar: 50 },
  { id: 'h2', zaman: new Date(Date.now() - 86400000 * 4).toISOString(), aciklama: 'İçerik doğrulandı (Metin)', miktar: 10 },
  { id: 'h3', zaman: new Date(Date.now() - 86400000 * 3).toISOString(), aciklama: 'İçerik doğrulandı (Anket)', miktar: 6 },
  { id: 'h4', zaman: new Date(Date.now() - 86400000 * 2).toISOString(), aciklama: 'Neon Çerçeve satın alındı', miktar: -15 },
  { id: 'h5', zaman: new Date(Date.now() - 86400000 * 1).toISOString(), aciklama: 'İçerik doğrulandı (Metin + Görsel)', miktar: 12 },
  { id: 'h6', zaman: new Date(Date.now() - 3600000 * 12).toISOString(), aciklama: 'İçerik doğrulandı (Metin)', miktar: 10 },
  { id: 'h7', zaman: new Date(Date.now() - 3600000 * 6).toISOString(), aciklama: 'İçerik doğrulandı (Kısmi)', miktar: 5 },
  { id: 'h8', zaman: new Date(Date.now() - 3600000 * 1).toISOString(), aciklama: 'İçerik doğrulandı (Metin + Görsel)', miktar: 12 },
]

export const demoGonderiler: Gonderi[] = [
  {
    id: 'g1',
    yazarId: 'user1',
    tur: 'metin',
    metin: 'Bugün harika bir kahve keşfettim. Bazen küçük detaylar tüm günü güzelleştirebiliyor.',
    gorselUrl: null,
    anketSecenekleri: null,
    olusturmaZamani: new Date(Date.now() - 3600000 * 24).toISOString(),
    yzBeyani: false,
    yorumSayisi: 3,
    yenidenPaylasimSayisi: 1,
    roketSayisi: 12,
    izlenimSayisi: 245,
    dogrulamaDurumu: 'gecti',
    dogrulamaSkoru: 85,
    kazanilanJeton: 10,
    gerekce: ['Özgünlük: Yüksek', 'Anlatım zenginliği: Yeterli'],
    metinParcalari: ['bugün', 'harik', 'kahve', 'keşfe', 'bazen', 'küçük', 'detay'],
    gorselHash: null
  },
  {
    id: 'g2',
    yazarId: 'user2',
    tur: 'metin',
    metin: 'Yapay zeka araçlarını günlük iş akışına entegre etmek inanılmaz bir zaman tasarrufu sağlıyor.',
    gorselUrl: null,
    anketSecenekleri: null,
    olusturmaZamani: new Date(Date.now() - 3600000 * 12).toISOString(),
    yzBeyani: true,
    yorumSayisi: 5,
    yenidenPaylasimSayisi: 2,
    roketSayisi: 28,
    izlenimSayisi: 530,
    dogrulamaDurumu: 'gecti',
    dogrulamaSkoru: 92,
    kazanilanJeton: 10,
    gerekce: ['Özgünlük: Çok Yüksek', 'Anlatım zenginliği: İyi'],
    metinParcalari: ['yapay', 'zekaa', 'araçl', 'günlü', 'enteg', 'inani', 'tasar'],
    gorselHash: null
  },
  {
    id: 'g3',
    yazarId: 'user3',
    tur: 'metin',
    metin: 'Bu hafta sonu kesinlikle dinlenmeye ayıracağım. Çok yorucu bir hafta oldu.',
    gorselUrl: null,
    anketSecenekleri: null,
    olusturmaZamani: new Date(Date.now() - 3600000 * 8).toISOString(),
    yzBeyani: false,
    yorumSayisi: 1,
    yenidenPaylasimSayisi: 0,
    roketSayisi: 5,
    izlenimSayisi: 120,
    dogrulamaDurumu: 'gecemedi',
    dogrulamaSkoru: 35,
    kazanilanJeton: 0,
    gerekce: ['Bu metin daha önce paylaşılmış bir gönderiyle büyük ölçüde örtüşüyor.'],
    metinParcalari: ['hafta', 'sonuk', 'kesin', 'dinle', 'ayira', 'yoruc'],
    gorselHash: null
  },
  {
    id: 'g4',
    yazarId: 'user1',
    tur: 'metin',
    metin: 'Bu hafta sonu kesinlikle dinlenmeye ayıracağım. Çok yorucu bir hafta oldu.',
    gorselUrl: null,
    anketSecenekleri: null,
    olusturmaZamani: new Date(Date.now() - 3600000 * 48).toISOString(), // older post that g3 copied
    yzBeyani: false,
    yorumSayisi: 8,
    yenidenPaylasimSayisi: 1,
    roketSayisi: 45,
    izlenimSayisi: 890,
    dogrulamaDurumu: 'gecti',
    dogrulamaSkoru: 75,
    kazanilanJeton: 10,
    gerekce: ['Özgünlük: Yeterli'],
    metinParcalari: ['hafta', 'sonuk', 'kesin', 'dinle', 'ayira', 'yoruc'],
    gorselHash: null
  },
  {
    id: 'g5',
    yazarId: 'user4',
    tur: 'metinGorsel',
    metin: 'Yeni çalışma masamın düzeni. Nihayet kablolardan kurtuldum!',
    gorselUrl: 'https://picsum.photos/seed/desk/600/400',
    anketSecenekleri: null,
    olusturmaZamani: new Date(Date.now() - 3600000 * 5).toISOString(),
    yzBeyani: false,
    yorumSayisi: 12,
    yenidenPaylasimSayisi: 3,
    roketSayisi: 110,
    izlenimSayisi: 1200,
    dogrulamaDurumu: 'gecti',
    dogrulamaSkoru: 88,
    kazanilanJeton: 12,
    gerekce: ['Özgünlük: Yüksek', 'Görsel kalite: İyi'],
    metinParcalari: ['yenic', 'çaliş', 'masam', 'düzen', 'nihay', 'kablo', 'kurtu'],
    gorselHash: 'a1b2c3d4'
  },
  {
    id: 'g6',
    yazarId: 'user1',
    tur: 'anket',
    metin: 'Sizce bir sonraki büyük teknolojik devrim hangi alanda olacak?',
    gorselUrl: null,
    anketSecenekleri: ['Kuantum Bilgisayarlar', 'Biyoteknoloji', 'Uzay Madenciliği'],
    olusturmaZamani: new Date(Date.now() - 3600000 * 2).toISOString(),
    yzBeyani: false,
    yorumSayisi: 24,
    yenidenPaylasimSayisi: 5,
    roketSayisi: 65,
    izlenimSayisi: 2100,
    dogrulamaDurumu: 'gecti',
    dogrulamaSkoru: 82,
    kazanilanJeton: 6,
    gerekce: ['Özgünlük: Yüksek', 'Etkileşim potansiyeli: İyi'],
    metinParcalari: ['sizce', 'sonra', 'büyük', 'tekno', 'devri', 'hangi', 'aland'],
    gorselHash: null
  },
  {
    id: 'g7',
    yazarId: 'user5',
    tur: 'metin',
    metin: 'a a a a a b b b b b c c c c c',
    gorselUrl: null,
    anketSecenekleri: null,
    olusturmaZamani: new Date(Date.now() - 3600000 * 1).toISOString(),
    yzBeyani: false,
    yorumSayisi: 0,
    yenidenPaylasimSayisi: 0,
    roketSayisi: 0,
    izlenimSayisi: 12,
    dogrulamaDurumu: 'gecemedi',
    dogrulamaSkoru: 15,
    kazanilanJeton: 0,
    gerekce: ['İçerik niteliği düşük: Anlamsız tekrar tespit edildi.'],
    metinParcalari: ['aaaaa', 'bbbbb', 'ccccc'],
    gorselHash: null
  },
  {
    id: 'g8',
    yazarId: 'user1',
    tur: 'metin',
    metin: 'Sürekli öğrenmek, gelişimin en temel anahtarıdır.',
    gorselUrl: null,
    anketSecenekleri: null,
    olusturmaZamani: new Date(Date.now() - 1800000).toISOString(),
    yzBeyani: false,
    yorumSayisi: 1,
    yenidenPaylasimSayisi: 0,
    roketSayisi: 8,
    izlenimSayisi: 95,
    dogrulamaDurumu: 'kismi',
    dogrulamaSkoru: 55,
    kazanilanJeton: 5,
    gerekce: ['Özgünlük: Yeterli', 'Uzunluk: Sınırda'],
    metinParcalari: ['sürek', 'öğren', 'geliş', 'temel', 'anaht'],
    gorselHash: null
  }
]

export const defaultState: AppState = {
  kullanici: {
    id: 'user1',
    kullaniciAdi: 'Ahmet Yılmaz',
    avatarUrl: 'https://i.pravatar.cc/150?u=user1',
    jetonBakiyesi: 120, // 120 as requested
    bugunKazanilan: 17,
    envanter: [],
    hesapOlusturmaTarihi: new Date(Date.now() - 86400000 * 30).toISOString()
  },
  gonderiler: demoGonderiler,
  hareketler: demoHareketler,
  magaza: demoMagaza
}
